from rdflib import Namespace

sfo = Namespace('https://nzsuperfund.co.nz/ontology/')
sfo_cls_ind_gics = Namespace('https://nzsuperfund.co.nz/ontology/CLS/Ind/gics/')
# sf_cu = Namespace('https://api.nzsuperfund.co.nz/custodian/')
# sf_mki = Namespace('https://api.nzsuperfund.co.nz/marketIndex/')
# sf_mk = Namespace('https://api.nzsuperfund.co.nz/market/')
# sf_pa = Namespace('https://api.nzsuperfund.co.nz/party/')
sfo_prt = Namespace('https://nzsuperfund.co.nz/ontology/PRT/')
sfo_fi = Namespace('https://nzsuperfund.co.nz/ontology/FI/')
sfo_cmn = Namespace('https://nzsuperfund.co.nz/ontology/CMN/')
sfo_cmn_ind_cur = Namespace('https://nzsuperfund.co.nz/ontology/CMN/Ind/Currency')
sfo_cls = Namespace('https://nzsuperfund.co.nz/ontology/CLS/')

owl = Namespace("http://www.w3.org/2002/07/owl#")
# rdf = Namespace('http://www.w3.org/1999/02/22-rdf-syntax-ns#')
# rdfs = Namespace('http://www.w3.org/2000/01/rdf-schema#')
skos = Namespace('http://www.w3.org/2004/02/skos/core#')
fibo_sec_sec_ast = Namespace('https://spec.edmcouncil.org/fibo/ontology/SEC/Securities/SecurityAssets/')
fibo_fbc_fi_fi = Namespace('https://spec.edmcouncil.org/fibo/ontology/FBC/FinancialInstruments/FinancialInstruments/')
fibo_sec_sec_idind = Namespace('https://spec.edmcouncil.org/fibo/ontology/SEC/Securities/SecuritiesIdentificationIndividuals/')
fibo_sec_sec_id = Namespace('https://spec.edmcouncil.org/fibo/ontology/SEC/Securities/SecuritiesIdentification/')
fibo_fbc_pas_fpas = Namespace('https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/')
fibo_fnd_arr_cls = Namespace('https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/ClassificationSchemes/')
fibo_sec_sec_iss = Namespace('https://spec.edmcouncil.org/fibo/ontology/SEC/Securities/SecuritiesIssuance/')
fibo_sec_eq_eq = Namespace('https://spec.edmcouncil.org/fibo/ontology/SEC/Equities/EquityInstruments/')
fibo_fnd_org_fm = Namespace('https://spec.edmcouncil.org/fibo/ontology/FND/Organizations/FormalOrganizations/')
fibo_fnd_rel_rel = Namespace('https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/')
fibo_fnd_acc_cur = Namespace('https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/CurrencyAmount/')
fibo_fnd_dt_fd = Namespace('https://spec.edmcouncil.org/fibo/ontology/FND/DatesAndTimes/FinancialDates/')
fibo_sec_sec_ast = Namespace('https://spec.edmcouncil.org/fibo/ontology/SEC/Securities/SecurityAssets/')
fibo_fi_ip = Namespace('https://spec.edmcouncil.org/fibo/ontology/FBC/FinancialInstruments/InstrumentPricing/')
fibo_fnd_acc_4217 = Namespace('https://spec.edmcouncil.org/fibo/ontology/FND/Accounting/ISO4217-CurrencyCodes/')
fibo_fnd_arr_rt = Namespace('https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Ratings/')
fibo_fnd_oac_own = Namespace("https://spec.edmcouncil.org/fibo/ontology/FND/OwnershipAndControl/Ownership/")
fibo_be_fct_pub = Namespace("https://spec.edmcouncil.org/fibo/ontology/BE/FunctionalEntities/Publishers/")
fibo_sec_fund_civ = Namespace("https://spec.edmcouncil.org/fibo/ontology/SEC/Funds/CollectiveInvestmentVehicles/")
fibo_fnd_arr_arr = Namespace("https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Arrangements/")
fibo_fnd_pty_pty = Namespace("https://spec.edmcouncil.org/fibo/ontology/FND/Parties/Parties/")
fibo_sec_sec_bsk = Namespace("https://spec.edmcouncil.org/fibo/ontology/SEC/Securities/Baskets/")
fibo_fnd_utl_alx = Namespace("https://spec.edmcouncil.org/fibo/ontology/FND/Utilities/Analytics/")

fibo_fnd_pty_pty = Namespace("https://spec.edmcouncil.org/fibo/ontology/FND/Parties/Parties/")
fibo_ind_mkt_bas = Namespace("https://spec.edmcouncil.org/fibo/ontology/IND/MarketIndices/BasketIndices/")

lcc_3166_1 = Namespace('https://www.omg.org/spec/LCC/Countries/ISO3166-1-CountryCodes/')
lcc_cr = Namespace('https://www.omg.org/spec/LCC/Countries/CountryRepresentation/')
lcc_lr = Namespace("https://www.omg.org/spec/LCC/Languages/LanguageRepresentation/")

rr = Namespace("http://www.w3.org/ns/r2rml#")
rml = Namespace("http://semweb.mmlab.be/ns/rml#")
